# Generated by Django 4.0.3 on 2022-09-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_used',
            field=models.CharField(default='Stack1 | stack2', max_length=100),
        ),
    ]
